### Add Item to Basket
POST http://localhost:8000/add-item-to-basket
Content-Type: application/json
Accept: application/json

{
  "product_id": "B00566S7QC",
  "basket_id": "2",
  "user_id": "2"
}

### Checkout Basket
POST http://localhost:8000/checkout-basket
Content-Type: application/json

{
  "basket_id": "example_basket_id",
  "user_id": "example_user_id"
}

### Get Categories
GET http://localhost:8000/categories

### Get Items by ASIN
GET http://localhost:8000/items/example_asin

### Get Items by Category
GET http://localhost:8000/categories/example_category
