### Add Item to Basket
POST http://localhost:8000/add-item-to-basket
Content-Type: application/json
Accept: application/json

{
  "product-id": "B00566S7QC",
  "basket-id": "4444s3",
  "user-id": "4444s3"
}

### Checkout Basket
POST http://localhost:8000/checkout-basket
Content-Type: application/json
Accept: application/json

{
  "basket-id": "4444s3",
  "user-id": "4444s3"
}

### Get Categories
GET http://localhost:8000/categories

### Get Items by ASIN
GET http://localhost:8000/items/B00566S7QC

### Get Items by Category
GET http://localhost:8000/categories/Camcorders
