### Add Item to Basket
POST http://localhost:8080/add-item-to-basket
Content-Type: application/json
Accept: application/json

{
  "product-id": "B00566S7QC",
  "basket-id": "4444",
  "user-id": "4444"
}

### Checkout Basket
POST http://localhost:8080/checkout-basket
Content-Type: application/json
Accept: application/json

{
  "basket-id": "4444",
  "user-id": "4444"
}

### Get Categories
GET http://localhost:8080/categories

### Get Items by ASIN
GET http://localhost:8080/items/B00566S7QC

### Get Items by Category
GET http://localhost:8080/categories/Camcorders
