version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8080 BlackFriday.wsgi:application
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    env_file:
      - .env

#  db:
#    image: postgres:13
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: blackFriday
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: admin

  prometheus:
    image: prom/prometheus:v2.48.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command: --config.file=/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana:10.2.3
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/datasources/dashboard.yaml
      - ./grafana/django-http-metric-dashboard.json:/etc/grafana/provisioning/dashboards/django-http-metric-dashboard.json
    depends_on:
      - prometheus

volumes:
  postgres_data:
