# Generated by Django 5.1 on 2024-08-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('basket_id', models.TextField(db_column='BasketId', primary_key=True, serialize=False)),
                ('product_id', models.TextField(db_column='ProductId')),
                ('user_id', models.TextField(db_column='UserId')),
                ('is_checked_out', models.BooleanField(db_column='IsCheckedOut')),
            ],
            options={
                'db_table': 'Baskets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_id', models.TextField(db_column='BasketId')),
                ('user_id', models.TextField(db_column='UserId')),
                ('items', models.TextField(db_column='Items')),
            ],
            options={
                'db_table': 'Invoices',
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('asin', models.CharField(db_comment='TRIAL', max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_comment='TRIAL', max_length=1500, null=True)),
                ('img_url', models.CharField(blank=True, db_column='imgUrl', db_comment='TRIAL', max_length=200, null=True)),
                ('product_url', models.CharField(blank=True, db_column='productUrl', db_comment='TRIAL', max_length=200, null=True)),
                ('stars', models.DecimalField(blank=True, db_comment='TRIAL', decimal_places=6, max_digits=28, null=True)),
                ('reviews', models.BigIntegerField(blank=True, db_comment='TRIAL', null=True)),
                ('price', models.DecimalField(blank=True, db_comment='TRIAL', decimal_places=6, max_digits=28, null=True)),
                ('is_best_seller', models.BooleanField(blank=True, db_column='isBestSeller', db_comment='TRIAL', null=True)),
                ('bought_in_last_month', models.BigIntegerField(blank=True, db_column='boughtInLastMonth', db_comment='TRIAL', null=True)),
                ('category_name', models.CharField(blank=True, db_column='categoryName', db_comment='TRIAL', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Products',
                'db_table_comment': 'TRIAL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCount',
            fields=[
                ('asin', models.TextField(db_column='Asin', primary_key=True, serialize=False)),
                ('count', models.IntegerField(db_column='Count')),
            ],
            options={
                'db_table': 'ProductCounts',
                'managed': False,
            },
        ),
    ]
