# Generated by Django 5.1 on 2024-08-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('basketid', models.TextField(db_column='BasketId')),
                ('productid', models.TextField(db_column='ProductId', primary_key=True, serialize=False)),
                ('userid', models.TextField(db_column='UserId')),
                ('ischeckedout', models.BooleanField(db_column='IsCheckedOut')),
            ],
            options={
                'db_table': 'Baskets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('basketid', models.TextField(db_column='BasketId')),
                ('userid', models.TextField(db_column='UserId', primary_key=True, serialize=False)),
                ('items', models.TextField(db_column='Items')),
            ],
            options={
                'db_table': 'Invoices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(blank=True, db_comment='TRIAL', max_length=200, null=True)),
                ('title', models.CharField(blank=True, db_comment='TRIAL', max_length=1500, null=True)),
                ('imgurl', models.CharField(blank=True, db_column='imgUrl', db_comment='TRIAL', max_length=200, null=True)),
                ('producturl', models.CharField(blank=True, db_column='productUrl', db_comment='TRIAL', max_length=200, null=True)),
                ('stars', models.DecimalField(blank=True, db_comment='TRIAL', decimal_places=6, max_digits=28, null=True)),
                ('reviews', models.BigIntegerField(blank=True, db_comment='TRIAL', null=True)),
                ('price', models.DecimalField(blank=True, db_comment='TRIAL', decimal_places=6, max_digits=28, null=True)),
                ('isbestseller', models.BooleanField(blank=True, db_column='isBestSeller', db_comment='TRIAL', null=True)),
                ('boughtinlastmonth', models.BigIntegerField(blank=True, db_column='boughtInLastMonth', db_comment='TRIAL', null=True)),
                ('categoryname', models.CharField(blank=True, db_column='categoryName', db_comment='TRIAL', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Products',
                'db_table_comment': 'TRIAL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCount',
            fields=[
                ('asin', models.TextField(db_column='Asin', primary_key=True, serialize=False)),
                ('count', models.IntegerField(db_column='Count')),
            ],
            options={
                'db_table': 'ProductCounts',
                'managed': False,
            },
        ),
    ]
